### ISSUE TITLE
locate file yourself error

### ISSUE THREAD

**Issue by hodanli** [WorldBrain/memex-local-sync#2]
i get this error on win 11.

![image](https://github.com/WorldBrain/memex-local-sync/assets/6535865/afc277bd-17f0-48bd-8a0d-62e57dc3f17b)

**Comment by blackforestboi** [comment]
Thanks for the note! 

Can you describe the steps you took to get here?
I am not a Windows user but this tells me that you have maybe created an Alias and this is looking for its source?

**Comment by hodanli** [comment]
I followed the standard procedure when installing apps on Windows:

1. Downloaded the file to my desktop.
2. Executed it.
3. A shortcut was created on the desktop.
4. I launched the shortcut.
5. I encountered an error.

I suspect the shortcut can't locate the necessary file on my computer. Despite searching thoroughly, I couldn’t find "Memex Local Sync Helper.exe" or even just "Helper.exe". The only related file I found was "Uninstall Memex Local Sync Helper.exe".

**Comment by sideone** [comment]
replicated on w11 pro/admin account.
![image](https://github.com/WorldBrain/memex-local-sync/assets/723468/b1923f67-a7cc-4646-83ed-163e3f81d27b)

**Comment by grygus** [comment]
Same on my Windows 10 machine, moreoever after manually unpacking installer .exe  and running Memex Local Sync Helper.exe, message says this application is not for my computer. I have standard i7 base pc running windows 10 with admin priv.

**Comment by mohamadiarch** [comment]
same on Windows 10.
https://community.memex.garden/t/memex-local-sync-helper-is-not-found/2216

**Comment by mohamadiarch** [comment]
I wish we could export and import our data without any extra apps.

**Comment by miguelmarcos** [comment]
I get the same error. Here are the steps I followed.
1. Downloaded Memex-Local-Sync-Helper-Setup.0.0.3.exe
2. Ran the above .exe and it displays an install window with a green bar
3. An error box comes up as the install proceeds. It states "Windows is searching for Memex Local Sync Helper.exe. To
locate the file yourself, click Browse."
4. Subsequently a "Problem with Shortcut" box appears indicating that the shortcut for Memex Local Sync Helper.exe does not work because it has changed or been moved.

I was able to locate the shortcut on the desktop. I looked at the properties. The target address for the shortcut is 
"C:\Users\migue\AppData\Local\Programs\memex-local-sync\Memex Local Sync Helper.exe" The folder memex-local-sync is present but inside this folder there is only item: Uninstall Memex Local Sync Helper.exe

Happy to assist with this in any way I can. I'd like to try the Obsidian sync and then subscribe to Memex.

Windows 11 Pro 22H2, Dell XP Pro 32gb/1tb (658gb free)
Was running Vivaldi, Obsidian, File Explorer, Clock

**Comment by hodanli** [comment]
my issue is resolved after the v0.0.4. if others confirm too, I can close the issue.

**Comment by grygus** [comment]
I can confirm, it is working now.

**Comment by hodanli** [comment]
resolved
