### ISSUE TITLE
Re-Select Obsidian Folder Doesn't Work

### ISSUE THREAD

**Issue by sanchitram1** [WorldBrain/memex-local-sync#6]
I'd like to select a new Obsidian Folder to sync to, but it doesn't work.  I open my Memex local sync helper app, and then from the chrome extension's settings, I keep clicking on "Select Obsidian Folder", but it doesn't work. 

Sync v0.0.4

Happy to provide more information if needed!

**Comment by blackforestboi** [comment]
Hey @sanchitram1 its likely because you tried to do that with a second extension, or reinstalled your current one?
We have a security mechanism to prevent more than one app, e.g. the extension to connect to that local server. 
In order to reset the selection, refresh the key here: 

<img width="244" alt="Screenshot 2023-11-08 at 10 18 22" src="https://github.com/WorldBrain/memex-local-sync/assets/7870039/21846245-746f-4098-817f-25cdb311b4b2">

**Comment by sanchitram1** [comment]
worked like a charm 🚀

also, apologies for not seeing this on your [Notion page](https://tutorials.memex.garden/tutorials/obsidian-and-logseq-sync):
```
Troubleshooting

1. Nothing happens when I click on the folder select
Did you uninstall and reinstall the extension at some point after setting up the Local Sync Helper? 
Then you maybe have to “Refresh the Sync Key”  via the Memex tray. 
It’s because we’ve built in a security mechanism to prevent other apps from connecting with the local helper. Now, only the first app that connects with the Helper can continue the communication. Refreshing the Sync Key resets that process. 
```
